<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ITMO.SymbolicComputations.Base\ITMO.SymbolicComputations.Base.csproj" />
      <ProjectReference Include="..\ITMO.SymbolicComputations.Workbench\ITMO.SymbolicComputations.Workbench.csproj" />
    </ItemGroup>

    <ItemGroup>

    </ItemGroup>
</Project>
